#!/usr/bin/env python3
"""Build the signage SDF atlas (spec §3.1: UI / neon / graffiti as SDF vector textures).

Rasterises every glyph used by the sign vocabulary with Noto Sans CJK JP Bold (SIL Open
Font License 1.1), converts it to a signed distance field, and writes:

  assets/sign_font_sdf.bin                 R8 atlas, kCols x kRows cells of kCell px
  engine/include/apex/sign_text_data.hpp   string table as glyph indices + atlas layout

Distance encoding: 0.5 = glyph edge, >0.5 inside, 1/kSpread of the value per cell pixel.

Requires: pillow, numpy, scipy, fonts-noto-cjk. Re-run after editing VOCAB.
"""
import os
import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT = "/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc"
FONT_INDEX_JP = 0  # the .ttc face order starts with "Noto Sans CJK JP"
CELL = 48          # atlas cell size (px)
SCALE = 4          # supersampling for the distance transform
SPREAD = 6.0       # distance range in cell pixels mapped to [0, 1]
COLS = 16

# Japanese signage and original (fictional) brand names. Nothing here is taken from any
# existing game's brand list.
VOCAB_JA = [
    "24時間営業", "ラーメン", "薬局", "酒場", "カラオケ", "ホテル", "質屋", "電脳", "義体修理",
    "未来", "夜市", "食堂", "両替", "占い", "営業中", "焼鳥", "寿司", "居酒屋", "麻雀", "ゲーム",
    "電気街", "整備工場", "喫茶", "中古", "激安", "新型", "記憶屋", "無料", "空室あり", "薬", "酒",
    "湯", "龍", "夢", "銀河", "月光", "極楽", "天国", "本日限定", "深夜食堂", "義眼", "修理",
    "闇市", "雨宿り", "屋台", "餃子", "回転", "密造", "高速", "駐車場", "非常口", "立入禁止",
]
VOCAB_LATIN = [
    "NEOTEK", "SYNAPSE", "HALCYON", "OPEN 24H", "BAR", "HOTEL", "NOODLES", "CYBERWARE", "TENKAI",
    "LUMEN", "KAIJU", "RONIN", "NOVA", "PULSE", "ZERO", "VOID", "APEX", "NIGHT MARKET", "ORBITAL",
    "HYPERION", "SAKURA", "KOI", "DATA", "LIVE", "SALE 35%", "NEW", "RAMEN", "TAXI", "CLINIC",
]
MAX_LEN = 12


def glyph_sdf(font, ch):
    big = CELL * SCALE
    img = Image.new("L", (big, big), 0)
    d = ImageDraw.Draw(img)
    # Centre the glyph in the cell using its ink bounding box.
    x0, y0, x1, y1 = d.textbbox((0, 0), ch, font=font)
    w, h = x1 - x0, y1 - y0
    d.text(((big - w) / 2 - x0, (big - h) / 2 - y0), ch, font=font, fill=255)
    inside = np.array(img) > 127
    if not inside.any():
        return np.zeros((CELL, CELL), np.uint8)
    dist_out = distance_transform_edt(~inside)
    dist_in = distance_transform_edt(inside)
    signed = (dist_in - dist_out) / SCALE  # in cell pixels, + inside
    v = 0.5 + signed / (2.0 * SPREAD)
    # Downsample by averaging SCALE x SCALE blocks.
    v = v.reshape(CELL, SCALE, CELL, SCALE).mean(axis=(1, 3))
    return (np.clip(v, 0.0, 1.0) * 255.0 + 0.5).astype(np.uint8)


def main():
    font = ImageFont.truetype(FONT, int(CELL * SCALE * 0.78), index=FONT_INDEX_JP)
    strings = [(s, True) for s in VOCAB_JA] + [(s, False) for s in VOCAB_LATIN]
    for s, _ in strings:
        assert len(s) <= MAX_LEN, s
    chars = sorted({c for s, _ in strings for c in s if c != " "})
    index = {c: i + 1 for i, c in enumerate(chars)}  # 0 = space / empty
    n = len(chars) + 1
    rows = (n + COLS - 1) // COLS
    atlas = np.zeros((rows * CELL, COLS * CELL), np.uint8)
    for c, i in index.items():
        r, col = divmod(i, COLS)
        atlas[r * CELL:(r + 1) * CELL, col * CELL:(col + 1) * CELL] = glyph_sdf(font, c)

    os.makedirs(os.path.join(ROOT, "assets"), exist_ok=True)
    atlas.tofile(os.path.join(ROOT, "assets", "sign_font_sdf.bin"))

    lines = [
        "// Generated by tools/gen_sign_font.py. Do not edit.",
        "// Glyphs: Noto Sans CJK JP Bold (SIL Open Font License 1.1).",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace apex::signtext {",
        f"inline constexpr std::uint32_t kCell = {CELL};",
        f"inline constexpr std::uint32_t kCols = {COLS};",
        f"inline constexpr std::uint32_t kRows = {rows};",
        f"inline constexpr std::uint32_t kAtlasWidth = {COLS * CELL};",
        f"inline constexpr std::uint32_t kAtlasHeight = {rows * CELL};",
        f"inline constexpr float kSpread = {SPREAD}f;",
        f"inline constexpr std::uint32_t kMaxLen = {MAX_LEN};",
        "// Long-vowel mark: rotated 90 degrees when text runs vertically.",
        f"inline constexpr std::uint32_t kGlyphChoonpu = {index.get('ー', 0)};",
        "",
        "// One sign string: glyph indices into the atlas (0 = space), length, and whether",
        "// it is Japanese (may be set vertically on blade signs).",
        "struct Entry {",
        f"    std::uint8_t glyphs[{MAX_LEN}];",
        "    std::uint8_t length;",
        "    bool japanese;",
        "};",
        "",
        f"inline constexpr std::uint32_t kJapaneseCount = {len(VOCAB_JA)};",
        f"inline constexpr std::uint32_t kLatinCount = {len(VOCAB_LATIN)};",
        "inline constexpr Entry kStrings[] = {",
    ]
    for s, ja in strings:
        g = [index.get(c, 0) if c != " " else 0 for c in s] + [0] * (MAX_LEN - len(s))
        lines.append(f"    {{{{{', '.join(map(str, g))}}}, {len(s)}, {'true' if ja else 'false'}}},  // {s}")
    lines += ["};", "", "}  // namespace apex::signtext", ""]
    with open(os.path.join(ROOT, "engine", "include", "apex", "sign_text_data.hpp"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"{len(chars)} glyphs, atlas {COLS * CELL}x{rows * CELL}, {len(strings)} strings")


if __name__ == "__main__":
    main()
