# Usage: cmake -DINPUT=<file> -DOUTPUT=<header> -DNAME=<identifier> -P embed_binary.cmake
# Emits apex::assets::<NAME> as std::span<const std::uint8_t>.
file(READ "${INPUT}" hex HEX)
string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")
file(WRITE "${OUTPUT}.tmp"
"// Generated by cmake/embed_binary.cmake from ${INPUT}. Do not edit.
#pragma once
#include <cstdint>
#include <span>

namespace apex::assets {
inline constexpr std::uint8_t ${NAME}_data[] = {${bytes}};
inline constexpr std::span<const std::uint8_t> ${NAME}{${NAME}_data};
}  // namespace apex::assets
")
file(COPY_FILE "${OUTPUT}.tmp" "${OUTPUT}" ONLY_IF_DIFFERENT)
