# Usage: cmake -DOUTPUT=<header> -DINPUTS="<a.spv>;<b.spv>" -P embed_spirv.cmake
# Emits apex::shaders::<name> as std::span<const std::uint32_t> for each SPIR-V file
# (name = file name with '.' -> '_', minus the .spv suffix).
set(content "// Generated by cmake/embed_spirv.cmake. Do not edit.\n#pragma once\n#include <cstdint>\n#include <span>\n\nnamespace apex::shaders {\n")
foreach(spv IN LISTS INPUTS)
    get_filename_component(fname "${spv}" NAME)
    string(REGEX REPLACE "\\.spv$" "" name "${fname}")
    string(REPLACE "." "_" name "${name}")
    file(READ "${spv}" hex HEX)
    # SPIR-V is little-endian 32-bit words: bytes b0 b1 b2 b3 -> 0xb3b2b1b0.
    string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," words "${hex}")
    string(APPEND content "inline constexpr std::uint32_t ${name}_data[] = {${words}};\n")
    string(APPEND content "inline constexpr std::span<const std::uint32_t> ${name}{${name}_data};\n")
endforeach()
string(APPEND content "}  // namespace apex::shaders\n")
file(WRITE "${OUTPUT}.tmp" "${content}")
file(COPY_FILE "${OUTPUT}.tmp" "${OUTPUT}" ONLY_IF_DIFFERENT)
